#!/usr/bin/env python3

import json
import time
import urllib.request
import xml.etree.ElementTree as ET
from email.utils import parsedate

news = []

with open("rss2pdf.conf", "r", encoding="utf-8") as config_file:
    config = json.load(config_file)

for url in config["urls"]:
    headers = {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 "
        "(KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "none",
        "Accept-Language": "en-US,en;q=0.8",
        "Connection": "keep-alive",
    }
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request) as response:
        tree = ET.ElementTree(ET.fromstring(response.read()))
        for channel in tree.findall("./channel"):
            chan_title = channel.find("title")
            assert chan_title is not None
            for item in channel.findall("./item"):
                for child in item:
                    if child.tag == "title":
                        title = child.text
                    elif child.tag == "description":
                        description = child.text
                    elif child.tag == "link":
                        link = child.text
                    elif child.tag == "pubDate":
                        parsed_date = parsedate(child.text)
                        assert parsed_date is not None
                        date = time.mktime(parsed_date)
                    elif child.tag in (
                        "author",
                        "guid",
                        "enclosure",
                        "{http://purl.org/rss/1.0/modules/content/}encoded",
                        "category",
                    ):
                        pass
                    else:
                        print(f"Unknown: {child.tag} - {child.text}")
                news.append((date, chan_title.text, title, description, link))


print(news)
